################################################################################
# Author : Christian Amstutz
# Date   : 2017-05-02
#
# This scripts cleans up the IP folders from files generated by Vivado.
################################################################################

# Read project settings from file
set current_dir [file dirname [info script]]
source [file join $current_dir project_settings.tcl]

set_property part $fpga_part [current_project]

# Remove the files generated during IP generation
# (only works if XML file of IP is available and up-to-date)
reset_target all [get_ips]

# Delete XML files of the IP blocks
foreach ip [get_ips] {
  set file_base [file rootname [get_property IP_FILE $ip]]
  file delete "$file_base.xml"
}
