################################################################################
# Author : Christian Amstutz
# Date   : 2017-04-26
#
# Script cleans up the IP folder from the files generated by Xilinx Vivado.
################################################################################

for ip_path in "$@"
do
   rm ./$ip_path/doc -r -f
   rm ./$ip_path/hdl -r -f
   rm ./$ip_path/sim -r -f
   rm ./$ip_path/synth -r -f
   rm ./$ip_path/*.veo -f
   rm ./$ip_path/*.vho -f
   rm ./$ip_path/*.xml -f
done
