################################################################################
# Author : Christian Amstutz
# Date   : 2017-05-18
#
# This scripts cleans up the IP folders from files generated by Xilinx Vivado.
################################################################################

# Read project settings from file
set current_dir [file dirname [info script]]
source [file join $current_dir project_settings.tcl]

set_property part $fpga_part [current_project]

# Add own IP repository to project
set_property ip_repo_paths $user_ip_repo [current_fileset]
update_ip_catalog

# Create list of non block design IPs
list non_bd_ips
foreach ip [get_ips] {
  set ip_filename [get_property IP_FILE $ip]
  if ![string match "*$bd_dir*" "$ip_filename"] {
    lappend non_bd_ips $ip
  }
}

foreach ip $non_bd_ips {
  # Remove the files generated during IP generation (only if XML file valid)
  reset_target all $ip

  # Delete XML files of the IP blocks
  set file_base [file rootname [get_property IP_FILE $ip]]
  file delete "$file_base.xml"
}

# Reset block designs (to come here)
